# Generated by Django 6.0.3 on 2026-03-27 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('phone', 'Điện thoại / Máy tính bảng'), ('laptop', 'Laptop / Máy tính xách tay'), ('pc', 'PC & Linh kiện máy tính')], max_length=20)),
                ('price', models.BigIntegerField()),
                ('original_new_price', models.BigIntegerField(blank=True, null=True)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('condition', models.CharField(choices=[('99', 'Như mới (99% - Không trầy xước)'), ('95', 'Tốt (95% - Trầy xước nhẹ)'), ('90', 'Khá (90% - Trầy xước nhiều, cấn móp)'), ('parts', 'Xác máy / Cần sửa chữa')], max_length=10)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_proof', models.FileField(blank=True, null=True, upload_to='products/videos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Product.product')),
            ],
        ),
    ]
